### PR TITLE
Re-formatting by VSCode Julia extension using its default settings.

### PR DESCRIPTION
**Pull request by Emmanuel-R8**

### CODE REVIEW

**Comment by ayushpatnaikgit** [comment]
@chiraganand this is outdated now and should be closed. But perhaps it's a good idea to try the Julia Formatter on the package.

**Comment by chiraganand** [comment]
Most of the changes in this PR are related to spacing around the operators so I am not sure if we should change the history because of this?

**Comment by ayushpatnaikgit** [comment]
This should be closed now. @chiraganand

**Comment by smishr** [comment]
Closing as very out of date. Running julia formatter is useful

**Pull request closed without merging**
